# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20170316_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='orderProducts',
            field=models.ManyToManyField(through='products.OrderDetails', to='products.Product'),
        ),
    ]
