# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_orders_orderproducts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='user',
        ),
        migrations.AddField(
            model_name='orders',
            name='name',
            field=models.CharField(default='na', max_length=128),
            preserve_default=False,
        ),
    ]
