# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_orders_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='name',
            field=models.CharField(default='a', max_length=128),
            preserve_default=False,
        ),
    ]
